// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: pkg/proto/hashtag_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHashTagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId  uint32                              `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	HashTag []string                            `protobuf:"bytes,2,rep,name=HashTag,proto3" json:"HashTag,omitempty"`
	TagUser []*CreateHashTagRequest_TagUserData `protobuf:"bytes,3,rep,name=TagUser,proto3" json:"TagUser,omitempty"`
}

func (x *CreateHashTagRequest) Reset() {
	*x = CreateHashTagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hashtag_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHashTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHashTagRequest) ProtoMessage() {}

func (x *CreateHashTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hashtag_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHashTagRequest.ProtoReflect.Descriptor instead.
func (*CreateHashTagRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hashtag_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHashTagRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreateHashTagRequest) GetHashTag() []string {
	if x != nil {
		return x.HashTag
	}
	return nil
}

func (x *CreateHashTagRequest) GetTagUser() []*CreateHashTagRequest_TagUserData {
	if x != nil {
		return x.TagUser
	}
	return nil
}

type HashTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *HashTagResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *HashTagResponse) Reset() {
	*x = HashTagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hashtag_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashTagResponse) ProtoMessage() {}

func (x *HashTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hashtag_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashTagResponse.ProtoReflect.Descriptor instead.
func (*HashTagResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hashtag_service_proto_rawDescGZIP(), []int{1}
}

func (x *HashTagResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HashTagResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HashTagResponse) GetData() *HashTagResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateHashTagRequest_TagUserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	HashTag string `protobuf:"bytes,2,opt,name=HashTag,proto3" json:"HashTag,omitempty"`
}

func (x *CreateHashTagRequest_TagUserData) Reset() {
	*x = CreateHashTagRequest_TagUserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hashtag_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHashTagRequest_TagUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHashTagRequest_TagUserData) ProtoMessage() {}

func (x *CreateHashTagRequest_TagUserData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hashtag_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHashTagRequest_TagUserData.ProtoReflect.Descriptor instead.
func (*CreateHashTagRequest_TagUserData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hashtag_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateHashTagRequest_TagUserData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateHashTagRequest_TagUserData) GetHashTag() string {
	if x != nil {
		return x.HashTag
	}
	return ""
}

type HashTagResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashTagIds     []uint32 `protobuf:"varint,1,rep,packed,name=hashTagIds,proto3" json:"hashTagIds,omitempty"`
	HashTagUserIds []uint32 `protobuf:"varint,2,rep,packed,name=HashTagUserIds,proto3" json:"HashTagUserIds,omitempty"`
}

func (x *HashTagResponse_Data) Reset() {
	*x = HashTagResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hashtag_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashTagResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashTagResponse_Data) ProtoMessage() {}

func (x *HashTagResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hashtag_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashTagResponse_Data.ProtoReflect.Descriptor instead.
func (*HashTagResponse_Data) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hashtag_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *HashTagResponse_Data) GetHashTagIds() []uint32 {
	if x != nil {
		return x.HashTagIds
	}
	return nil
}

func (x *HashTagResponse_Data) GetHashTagUserIds() []uint32 {
	if x != nil {
		return x.HashTagUserIds
	}
	return nil
}

var File_pkg_proto_hashtag_service_proto protoreflect.FileDescriptor

var file_pkg_proto_hashtag_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x61, 0x73, 0x68,
	0x74, 0x61, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x62, 0x65, 0x75, 0x2e, 0x75, 0x73, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61,
	0x67, 0x22, 0xd5, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68,
	0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x12, 0x4a, 0x0a, 0x07,
	0x54, 0x61, 0x67, 0x55, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e,
	0x62, 0x65, 0x75, 0x2e, 0x75, 0x73, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x54, 0x61, 0x67, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x07, 0x54, 0x61, 0x67, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x3f, 0x0a, 0x0b, 0x54, 0x61, 0x67, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x22, 0xc9, 0x01, 0x0a, 0x0f, 0x48, 0x61,
	0x73, 0x68, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x62, 0x65, 0x75, 0x2e,
	0x75, 0x73, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x4e, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a,
	0x0a, 0x68, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x0a, 0x68, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x49, 0x64, 0x73, 0x12, 0x26, 0x0a,
	0x0e, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0e, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x73, 0x32, 0x9e, 0x02, 0x0a, 0x0e, 0x48, 0x61, 0x73, 0x68, 0x74, 0x61,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x12, 0x24, 0x2e, 0x62, 0x65, 0x75, 0x2e,
	0x75, 0x73, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x62, 0x65, 0x75, 0x2e, 0x75, 0x73, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67,
	0x2e, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48, 0x61, 0x73, 0x68,
	0x54, 0x61, 0x67, 0x12, 0x24, 0x2e, 0x62, 0x65, 0x75, 0x2e, 0x75, 0x73, 0x2e, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62, 0x65, 0x75, 0x2e,
	0x75, 0x73, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x12, 0x24, 0x2e,
	0x62, 0x65, 0x75, 0x2e, 0x75, 0x73, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61, 0x67, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62, 0x65, 0x75, 0x2e, 0x75, 0x73, 0x2e, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_hashtag_service_proto_rawDescOnce sync.Once
	file_pkg_proto_hashtag_service_proto_rawDescData = file_pkg_proto_hashtag_service_proto_rawDesc
)

func file_pkg_proto_hashtag_service_proto_rawDescGZIP() []byte {
	file_pkg_proto_hashtag_service_proto_rawDescOnce.Do(func() {
		file_pkg_proto_hashtag_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_hashtag_service_proto_rawDescData)
	})
	return file_pkg_proto_hashtag_service_proto_rawDescData
}

var file_pkg_proto_hashtag_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_hashtag_service_proto_goTypes = []interface{}{
	(*CreateHashTagRequest)(nil),             // 0: beu.us.hashtag.CreateHashTagRequest
	(*HashTagResponse)(nil),                  // 1: beu.us.hashtag.HashTagResponse
	(*CreateHashTagRequest_TagUserData)(nil), // 2: beu.us.hashtag.CreateHashTagRequest.TagUserData
	(*HashTagResponse_Data)(nil),             // 3: beu.us.hashtag.HashTagResponse.Data
}
var file_pkg_proto_hashtag_service_proto_depIdxs = []int32{
	2, // 0: beu.us.hashtag.CreateHashTagRequest.TagUser:type_name -> beu.us.hashtag.CreateHashTagRequest.TagUserData
	3, // 1: beu.us.hashtag.HashTagResponse.data:type_name -> beu.us.hashtag.HashTagResponse.Data
	0, // 2: beu.us.hashtag.HashtagService.CreateHashTag:input_type -> beu.us.hashtag.CreateHashTagRequest
	0, // 3: beu.us.hashtag.HashtagService.RemoveHashTag:input_type -> beu.us.hashtag.CreateHashTagRequest
	0, // 4: beu.us.hashtag.HashtagService.UpdateHashTag:input_type -> beu.us.hashtag.CreateHashTagRequest
	1, // 5: beu.us.hashtag.HashtagService.CreateHashTag:output_type -> beu.us.hashtag.HashTagResponse
	1, // 6: beu.us.hashtag.HashtagService.RemoveHashTag:output_type -> beu.us.hashtag.HashTagResponse
	1, // 7: beu.us.hashtag.HashtagService.UpdateHashTag:output_type -> beu.us.hashtag.HashTagResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_hashtag_service_proto_init() }
func file_pkg_proto_hashtag_service_proto_init() {
	if File_pkg_proto_hashtag_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_hashtag_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHashTagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hashtag_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashTagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hashtag_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHashTagRequest_TagUserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hashtag_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashTagResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_hashtag_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_hashtag_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_hashtag_service_proto_depIdxs,
		MessageInfos:      file_pkg_proto_hashtag_service_proto_msgTypes,
	}.Build()
	File_pkg_proto_hashtag_service_proto = out.File
	file_pkg_proto_hashtag_service_proto_rawDesc = nil
	file_pkg_proto_hashtag_service_proto_goTypes = nil
	file_pkg_proto_hashtag_service_proto_depIdxs = nil
}
